---
image:
  repository: gcr.io/planet-4-151612/brb
pagespeed:
  enabled: false

openresty:
  geoip:
    enabled: false
    accountid: ""
    license: ""
  cloudflare:
    enabled: false

nginxingress:
  name: global-brb-static-nginx2
  tls: true
